---
title: "Introduction"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(latexpdf)
```


This is the term project of BDS 522, Fall 2018, which is about "New York City Demographic Information (by zipcode regions) and Housing Prices Analyses". 

##Motivation

The motivation for the project is the curiosity of demographic information and housing prices information in New York City which use the public open source dataset: Zipcode with demograhpic statistics(See Zipcode.csv)) and "Summary of Neighborhood Sales for Manhattan for Class 1-, 2-. and 3- Family Home 2009" (See FamilyHome_Sales.csv) to find out information to support the decision making of potential investment oppotunnites. The priority is to use the descriptive statistics analysis to know the basic information of datasets.Then use more advanced statistics to make comparisions of distributions. Based on the literature review and past online journals. Demogprahic information plays a key role in determining the living environment and the future growth.



##Background

It is interesting to know how the demographic information in different zip code regions vary. The original idea was to combine more parameters together. Due to there is no common factor between two datasets, it is more realistic to analyze them seperately. Conclusions will be made based on the individual dataset. 

####Data Source
These two datasets are from NYC Open Data for research purpose: 

Demographic information is included by zip code in NYC 
https://data.cityofnewyork.us/City-Government/Demographic-Statistics-By-Zip-Code/kku6-nxdu

"Summary of Neighborhood Sales for Manhattan for Class 1-, 2- and 3-Family homes - 2009"
https://data.cityofnewyork.us/Housing-Development/DOF-Summary-of-Neighborhood-Sales-for-Manhattan-fo/5yay-3jd5




##Literature Review

1. Engelhardt, G. V., & Poterba, J. M. (1991) reveals how demographic chanegs and house prices associated in their paper based on time series correlation. Also, they comparied changes in Canadian housing market and the one in the United States. Age structure in United States and Canada was very similiar in 1989. Time trend, user cost and GNP are included in the regression to find out the relationship between demographic factors and housing prices. 


2. Lindh, T., & Malmberg, B. (2008) indicates the relationship between age distribution and housing demand by using the regression with different age groups. The housing price regression equation shows that the aging population can negatively affect the residential construction. Residengtal inbvestment is an independent factor of the housing prices. 


3. Patricia Gober reveals the association between the population and housing processes at different levels from local to national. Paper analysis concepts and ideas of urban demography and connections around the worlds. But does not use quantitative models and statistical analysis. 


##Hypotheses

1. Zipcode
     I) The null hypothesis: there is no difference between the demographic groups, Black - Non Hispanic and White.Non Hispanic.  (mean1 - mean2 = 0) 
     II) The alternative hypothesis: there is a difference between the demographic groups, Black - Non Hispanic and White.Non Hispanic.  (mean1 - mean2 != 0)


2. Family Homes Sales
     I) The null hypothesis: the means of the highest housing prices and lowest housing prices are the same  (mean1 - mean2 = 0)  
     II) The alternative hypothesis: the means of the highest housing prices and lowest housing prices are not the same (mean1 - mean2 != 0)


These are hypotheses generated by specific group comparisons. More tests are made using more combinations to find out statistical information. 

###Reference
Engelhardt, G. V., & Poterba, J. M. (1991). House prices and demographic change: Canadian evidence. Regional Science and Urban Economics, 21(4), 539-546.

Gober, P. (1992). Urban housing demography. Progress in Human Geography, 16(2), 171-189.

Lindh, T., & Malmberg, B. (2008). Demography and housing demand—what can we learn from residential construction data?. Journal of Population Economics, 21(3), 521-539.




